### ISSUE TITLE
ror-app should use same stylesheet as ror-site

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-site#11]

**Comment by cazinc** [comment]
I think this is resolved actually @mariagould as we've moved the stylesheet back into the site (it now lives in ../themes/hugo-ror/static/css/hugo-ror.css

**Comment by mariagould** [comment]
Excellent! Thanks so much.

**Comment by mfenner** [comment]
This is not fully resolved, as the search frontend (`ror-app`) still uses the old stylesheet. Let me work on having the `ror-app` use the same new stylesheet.

**Comment by mariagould** [comment]
Hi @cazinc I'd like to update the link colors in the ROR stylesheet. Is this something that you are able to do?

We are working on updating the Search frontend (ror.org/search) to use the same stylesheet but the current link color (#DA3200) does not look great on the Search page given how many links are present (see dev.ror.org/search). Can we use a variation on the ROR teal instead (something like #1F7F67)?

**Comment by cazinc** [comment]
I’m away but my colleague @bcgwebdesign  will be able to help. Bruce can you help @mariagould with this?

**Comment by bcgwebdesign** [comment]
Hi @mariagould , let me get up to speed with this today - it's a while since I've worked on ROR. Will come back here if I've any questions.

**Comment by bcgwebdesign** [comment]
I've had a look and hugo-ror.css looks like this is where the color is set.
The file is here ror-site/themes/hugo-ror/static/css/hugo-ror.css
And line 13772 the color of the link is set to #da3200
It looks like the selector should only change it on links within .card classed html elements so shouldn't affect anything else - but worth checking on a dev build of course.

I'm not sure if you want me to make the change on the dev branch  @mariagould ? I've not worked on the ror-site since very early days.

Also looking at the rest of this thread - I assume that the change in this .css file will then be picked up by the site search app side of things - ie it actually references this file rather than we have to manually duplicate some change over to the other repo?

**Comment by mariagould** [comment]
Hi Bruce - thank you for helping! Dev branch should be fine; this is where Zach has set up previous changes. 

The Search app is not currently referencing the style sheet for the main site but we want it to, which is what prompted this request because the link color #da3200 does not work when applied to the Search frontend (you can see this currently on https://dev.ror.org/search as opposed to https://ror.org/search). @mfenner can weigh in on further specifics of how ror-app is set up.

**Comment by mariagould** [comment]
Hi @bcgwebdesign @cazinc just checking in on this! Let me know if you need anything.

**Comment by cazinc** [comment]
Hi @mariagould sorry for the delay, Bruce was unclear about the setup of the ror site so I'm picking this up again. 

@mfenner so far as I can see the search functionality isn't in the site's repo, so we're unable to make any changes to it. Can you help clarify how things are setup?

**Comment by mfenner** [comment]
The search sub-site is using the CSS from the community site as an external stylesheet, so all CSS changes should be made there. The source code (an Ember.js app) is at  ror-community/ror-app.

**Comment by cazinc** [comment]
Hi @mfenner thanks. I hadn't realised that the dev site was pointed at the live site's CSS, and had been looking at the live site, which seems to still be pointed at its own internal CSS. 

@mariagould #da3200 is a red colour, and if I look at the dev site search this is the colour that shows. If you want the green it is #53BAA1. The confusion here too is perhaps that the dev site search is pointed at CSS on the live site. Might be better if we talk this one through on Slack. 

@mfenner thanks for pointing out where the search source is, I wasn't aware of this.

**Comment by cazinc** [comment]
Links in search on the dev site are now using #53baa1 @mariagould. You can review at https://dev.ror.org/search. If all is well this would just need merged into master branch to make it live.

**Comment by cazinc** [comment]
Just a wee reminder/note to myself and Martin that the dev site version of ember is pointed at https://dev.ror.org/css/hugo-ror.css now. once this is pushed live, the master branch of ror app will need to be repointed at https://ror.org/css/hugo-ror.css (without the **dev**).

**Comment by mariagould** [comment]
Thanks @cazinc the links on the search page look good. It doesn't look like the color isn't updated on the other pages, though - will that happen when we do the repointing?

**Comment by mariagould** [comment]
@cazinc @mfenner are there any remaining tasks here or can we close this out?

**Comment by cazinc** [comment]
Nothing that I'm aware of @mariagould save the final tweak when this goes live, per my comment from 16 March. That can happen at the last minute.

**Comment by mfenner** [comment]
LGTM.
